# Generated by Django 2.1.15 on 2020-03-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='cover',
        ),
    ]
